export const EVENT = {
    EVENT_ADD_IMAGE: 'EVENT_ADD_IMAGE',

    EVENT_SHOW_IMAGE: 'EVENT_SHOW_IMAGE',

    EVENT_INITIALIZING: 'EVENT_INITIALIZING',

    EVENT_START_WATCH_ON: "EVENT_START_WATCH_ON",

    EVENT_STOP_WATCH : 'EVENT_STOP_WATCH'
}

